name: computational-photography
dependencies:
  - python=3.6
  - matplotlib=3.0.1
  - numpy=1.19.1
  - scipy=1.1.0
  - cvxpy=1.1.3
  - pytest=6.1.1
  - pip=21.0.1
  - conda-forge::nb_conda
  - pip:
      - opencv-contrib-python==4.0.0.21
